.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. baddcoin_qt test_baddcoin_qt
clean: FORCE
	$(MAKE) -C .. baddcoin_qt_clean test_baddcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_baddcoin_qt_check
baddcoin-qt baddcoin-qt.exe: FORCE
	 $(MAKE) -C .. baddcoin_qt
